// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metapb.proto

/*
Package metapb is a generated protocol buffer package.

It is generated from these files:
	metapb.proto

It has these top-level messages:
	Label
	Cluster
	Peer
	CellEpoch
	Cell
	Store
*/
package metapb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoreState int32

const (
	StoreState_UP        StoreState = 0
	StoreState_Down      StoreState = 1
	StoreState_Tombstone StoreState = 2
)

var StoreState_name = map[int32]string{
	0: "UP",
	1: "Down",
	2: "Tombstone",
}
var StoreState_value = map[string]int32{
	"UP":        0,
	"Down":      1,
	"Tombstone": 2,
}

func (x StoreState) Enum() *StoreState {
	p := new(StoreState)
	*p = x
	return p
}
func (x StoreState) String() string {
	return proto.EnumName(StoreState_name, int32(x))
}
func (x *StoreState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StoreState_value, data, "StoreState")
	if err != nil {
		return err
	}
	*x = StoreState(value)
	return nil
}
func (StoreState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Label struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Label) Reset()                    { *m = Label{} }
func (m *Label) String() string            { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()               {}
func (*Label) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Label) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Cluster struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	MaxReplicas      *uint32 `protobuf:"varint,2,opt,name=maxReplicas" json:"maxReplicas,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Cluster) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Cluster) GetMaxReplicas() uint32 {
	if m != nil && m.MaxReplicas != nil {
		return *m.MaxReplicas
	}
	return 0
}

type Peer struct {
	Id               *uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	StoreID          *uint64 `protobuf:"varint,2,opt,name=storeID" json:"storeID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Peer) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Peer) GetStoreID() uint64 {
	if m != nil && m.StoreID != nil {
		return *m.StoreID
	}
	return 0
}

type CellEpoch struct {
	ConfVer          *uint64 `protobuf:"varint,1,opt,name=confVer" json:"confVer,omitempty"`
	CellVer          *uint64 `protobuf:"varint,2,opt,name=cellVer" json:"cellVer,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CellEpoch) Reset()                    { *m = CellEpoch{} }
func (m *CellEpoch) String() string            { return proto.CompactTextString(m) }
func (*CellEpoch) ProtoMessage()               {}
func (*CellEpoch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CellEpoch) GetConfVer() uint64 {
	if m != nil && m.ConfVer != nil {
		return *m.ConfVer
	}
	return 0
}

func (m *CellEpoch) GetCellVer() uint64 {
	if m != nil && m.CellVer != nil {
		return *m.CellVer
	}
	return 0
}

type Cell struct {
	Id               *uint64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Start            []byte     `protobuf:"bytes,2,opt,name=start" json:"start,omitempty"`
	End              []byte     `protobuf:"bytes,3,opt,name=end" json:"end,omitempty"`
	Epoch            *CellEpoch `protobuf:"bytes,4,opt,name=epoch" json:"epoch,omitempty"`
	Peers            []*Peer    `protobuf:"bytes,5,rep,name=peers" json:"peers,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Cell) Reset()                    { *m = Cell{} }
func (m *Cell) String() string            { return proto.CompactTextString(m) }
func (*Cell) ProtoMessage()               {}
func (*Cell) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Cell) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Cell) GetStart() []byte {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Cell) GetEnd() []byte {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Cell) GetEpoch() *CellEpoch {
	if m != nil {
		return m.Epoch
	}
	return nil
}

func (m *Cell) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Store struct {
	Id               *uint64     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Address          *string     `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Lables           []*Label    `protobuf:"bytes,3,rep,name=lables" json:"lables,omitempty"`
	State            *StoreState `protobuf:"varint,4,opt,name=state,enum=metapb.StoreState" json:"state,omitempty"`
	ClientAddress    *string     `protobuf:"bytes,5,opt,name=clientAddress" json:"clientAddress,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Store) Reset()                    { *m = Store{} }
func (m *Store) String() string            { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()               {}
func (*Store) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Store) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Store) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *Store) GetLables() []*Label {
	if m != nil {
		return m.Lables
	}
	return nil
}

func (m *Store) GetState() StoreState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return StoreState_UP
}

func (m *Store) GetClientAddress() string {
	if m != nil && m.ClientAddress != nil {
		return *m.ClientAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Label)(nil), "metapb.Label")
	proto.RegisterType((*Cluster)(nil), "metapb.Cluster")
	proto.RegisterType((*Peer)(nil), "metapb.Peer")
	proto.RegisterType((*CellEpoch)(nil), "metapb.CellEpoch")
	proto.RegisterType((*Cell)(nil), "metapb.Cell")
	proto.RegisterType((*Store)(nil), "metapb.Store")
	proto.RegisterEnum("metapb.StoreState", StoreState_name, StoreState_value)
}

func init() { proto.RegisterFile("metapb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0xbd, 0x79, 0xb8, 0xbd, 0x9d, 0x36, 0x55, 0xae, 0xd5, 0x45, 0x96, 0x51, 0x74, 0x11, 0x11,
	0x12, 0x05, 0x75, 0xcb, 0x02, 0xa1, 0x96, 0x05, 0x12, 0x8b, 0xca, 0x05, 0xf6, 0x4e, 0x32, 0x88,
	0x08, 0x37, 0x8e, 0x62, 0x97, 0xc7, 0x37, 0xf0, 0x23, 0x7c, 0x26, 0xb2, 0x93, 0xf0, 0x10, 0xdd,
	0xf9, 0xcc, 0x99, 0x33, 0x67, 0xe6, 0x18, 0x26, 0x5b, 0xd4, 0xbc, 0xce, 0xe6, 0x75, 0x23, 0xb5,
	0xa4, 0x83, 0x16, 0x25, 0x27, 0x40, 0xae, 0x79, 0x86, 0x82, 0x86, 0xe0, 0x3d, 0xe2, 0x6b, 0xe4,
	0xc4, 0x4e, 0x3a, 0x62, 0xe6, 0x49, 0x67, 0x40, 0x9e, 0xb8, 0xd8, 0x61, 0xe4, 0xda, 0x5a, 0x0b,
	0x92, 0x33, 0x18, 0x2e, 0xc5, 0x4e, 0x69, 0x6c, 0xe8, 0x14, 0xdc, 0xb2, 0xb0, 0x0a, 0x9f, 0xb9,
	0x65, 0x41, 0x63, 0x18, 0x6f, 0xf9, 0x0b, 0xc3, 0x5a, 0x94, 0x39, 0x57, 0x56, 0x16, 0xb0, 0xef,
	0xa5, 0xe4, 0x14, 0xfc, 0x35, 0xee, 0x51, 0x46, 0x30, 0x54, 0x5a, 0x36, 0x78, 0xb5, 0xb2, 0x2a,
	0x9f, 0xf5, 0x30, 0x39, 0x87, 0xd1, 0x12, 0x85, 0xb8, 0xac, 0x65, 0xfe, 0x60, 0xda, 0x72, 0x59,
	0xdd, 0xdf, 0x61, 0xd3, 0x69, 0x7b, 0x68, 0x19, 0x14, 0xc2, 0x30, 0xdd, 0x80, 0x0e, 0x26, 0x6f,
	0x0e, 0xf8, 0x66, 0xc2, 0x2f, 0xcf, 0x19, 0x10, 0xa5, 0x79, 0xa3, 0xad, 0x60, 0xc2, 0x5a, 0x60,
	0x62, 0xc0, 0xaa, 0x88, 0x3c, 0x5b, 0x33, 0x4f, 0x7a, 0x08, 0x04, 0x8d, 0x7b, 0xe4, 0xc7, 0x4e,
	0x3a, 0x5e, 0xfc, 0x9b, 0x77, 0x39, 0x7e, 0xae, 0xc5, 0x5a, 0x9e, 0x26, 0x40, 0x6a, 0xc4, 0x46,
	0x45, 0x24, 0xf6, 0xd2, 0xf1, 0x62, 0xd2, 0x37, 0x9a, 0x8b, 0x59, 0x4b, 0x25, 0xef, 0x0e, 0x90,
	0x8d, 0x39, 0x6d, 0x5f, 0x04, 0xbc, 0x28, 0x1a, 0x54, 0xaa, 0xcb, 0xbb, 0x87, 0xf4, 0x00, 0x06,
	0x82, 0x67, 0x02, 0x55, 0xe4, 0xd9, 0xc1, 0x41, 0x3f, 0xd8, 0x7e, 0x1c, 0xeb, 0x48, 0x9a, 0xda,
	0x7b, 0x34, 0xda, 0x3d, 0xa7, 0x0b, 0xda, 0x77, 0x59, 0xbb, 0x8d, 0x61, 0x58, 0xdb, 0x40, 0xff,
	0x43, 0x90, 0x8b, 0x12, 0x2b, 0x7d, 0xd1, 0x19, 0x12, 0x6b, 0xf8, 0xb3, 0x78, 0x74, 0x0c, 0xf0,
	0x25, 0xa5, 0x03, 0x70, 0x6f, 0xd7, 0xe1, 0x1f, 0xfa, 0x17, 0xfc, 0x95, 0x7c, 0xae, 0x42, 0x87,
	0x06, 0x30, 0xba, 0x91, 0xdb, 0x4c, 0x69, 0x59, 0x61, 0xe8, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x32, 0x36, 0x64, 0xfc, 0x5f, 0x02, 0x00, 0x00,
}
